datastore:
  kind: mdp
  config_path: cosmo.datastore.yaml
datastore_boundary:
  kind: mdp
  config_path: era5.datastore.yaml
  variable_mapping:
    # Surface variables
    U_10M: 10m_u_component_of_wind
    T_2M: 2m_temperature
    V_10M: 10m_v_component_of_wind
    PMSL: mean_sea_level_pressure
    PS: surface_pressure
    TOT_PREC: total_precipitation
    # Height level variables
    U: u_component_of_wind
    V: v_component_of_wind
    T: temperature
    QV: specific_humidity
    W: vertical_velocity

training:
  state_feature_weighting:
    __config_class__: ManualStateFeatureWeighting
    weights:
      U_10M: 1.0
      T_2M: 1.0
      V_10M: 1.0
      PMSL: 1.0
      PS: 1.0
      TOT_PREC: 1.0
      ASHFL_S: 1.0
      ASOB_S: 1.0
      ATHB_S: 1.0
      U_lev_6: 0.125
      U_lev_12: 0.125
      U_lev_20: 0.125
      U_lev_27: 0.125
      U_lev_31: 0.125
      U_lev_39: 0.125
      U_lev_45: 0.125
      U_lev_60: 0.125
      V_lev_6: 0.125
      V_lev_12: 0.125
      V_lev_20: 0.125
      V_lev_27: 0.125
      V_lev_31: 0.125
      V_lev_39: 0.125
      V_lev_45: 0.125
      V_lev_60: 0.125
      PP_lev_6: 0.125
      PP_lev_12: 0.125
      PP_lev_20: 0.125
      PP_lev_27: 0.125
      PP_lev_31: 0.125
      PP_lev_39: 0.125
      PP_lev_45: 0.125
      PP_lev_60: 0.125
      T_lev_6: 0.125
      T_lev_12: 0.125
      T_lev_20: 0.125
      T_lev_27: 0.125
      T_lev_31: 0.125
      T_lev_39: 0.125
      T_lev_45: 0.125
      T_lev_60: 0.125
      QV_lev_6: 0.125
      QV_lev_12: 0.125
      QV_lev_20: 0.125
      QV_lev_27: 0.125
      QV_lev_31: 0.125
      QV_lev_39: 0.125
      QV_lev_45: 0.125
      QV_lev_60: 0.125
      W_lev_6: 0.125
      W_lev_12: 0.125
      W_lev_20: 0.125
      W_lev_27: 0.125
      W_lev_31: 0.125
      W_lev_39: 0.125
      W_lev_45: 0.125
      W_lev_60: 0.125
  output_clamping:
    lower:
      TOT_PREC: 0.0
      QV_lev_6: 0.0
      QV_lev_12: 0.0
      QV_lev_20: 0.0
      QV_lev_27: 0.0
      QV_lev_31: 0.0
      QV_lev_39: 0.0
      QV_lev_45: 0.0
      QV_lev_60: 0.0