
image = "/iopsstor/scratch/cscs/sadamov/my_pytorch.sqsh"

mounts = [
    "/users",
    "/capstor",
    "/iopsstor",
    "/iopsstor/scratch/cscs/sadamov/pyprojects_data/neural-lam",
]
writable = true

[env]
LD_LIBRARY_PATH = "/usr/local/cuda/lib64:/opt/hpcx/ucc/lib/:/opt/hpcx/ucx/lib:/usr/local/cuda/compat/lib.real:/external/lib:/usr/local/lib/python3.10/dist-packages/torch/lib:/usr/local/lib/python3.10/dist-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64"
XDG_CONFIG_HOME = "/root/.config"
HTTP_PROXY = "http://proxy.cscs.ch:8080"
HTTPS_PROXY = "http://proxy.cscs.ch:8080"
CONDA_AUTO_ACTIVATE_BASE = "false"
CONDA_DEFAULT_ENV = ""

[annotations]
com.hooks.aws_ofi_nccl.enabled = "true"
com.hooks.aws_ofi_nccl.variant = "cuda12"
