datastore:
  kind: mdp
  config_path: cosmo.datastore.yaml
datastore_boundary:
  kind: mdp
  config_path: era5.datastore.yaml
  variable_mapping:
    T_2M: 2m_temperature
training:
  state_feature_weighting:
    __config_class__: ManualStateFeatureWeighting
    weights:
      T_2M: 1.0
  output_clamping:
    lower:
      T_2M: 0.0
